version: '3.3'
services:
  bitgert-node:
    container_name: bitgert-node
    hostname: bitgert-node
    networks:
      - bitgert
    build:
      context: ./bitgert
      dockerfile: Dockerfile
      args:
        - ADDRESS=${ADDRESS}
        - PASSWORD=${PASSWORD}
        - PRIVATE_KEY=${PRIVATE_KEY}
        - BOOTNODES=${BITGERT_BOOTNODES}
    ports:
      - "8545:8545/tcp"
      - "8546:8546/tcp"
      - "30303:30303/udp"
    restart: always
  astar-node:
    container_name: astar-node
    hostname: astar-node
    networks:
      - astar
    build: 
      context: ./astar
      dockerfile: Dockerfile
    ports:
      - "30333:30333/udp"
      - "9944:9944/tcp"
      - "9933:9933/tcp"
    restart: always
  dashboard:
    container_name: dashboard
    hostname: dashboard
    networks:
      - dashboard
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "22900:22900/tcp"
  proxy:
    container_name: proxy
    image: proxy-vef:${IMAGE_TAG}
    hostname: localhost
    networks:
      - bitgert
      - dashboard
      - astar
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 32000:80
    depends_on:
      - bitgert-node
      - astar-node
      - dashboard
networks:
  bitgert:
    external: false
  dashboard:
    external: false
  astar:
    external: false